services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=wsgi.py
    volumes:
      - ./auth-service:/app
    depends_on:
      auth-db:
        condition: service_healthy

  auth-grpc:
    build: ./auth-service
    container_name: auth-grpc
    command: python grpc_server.py
    ports:
      - "50051:50051"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/proto
    volumes:
      - ./auth-service:/app
      - ./proto:/app/proto
    depends_on:
      auth-db:
        condition: service_healthy

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/proto
    volumes:
      - ./booking-service:/app
      - ./proto:/app/proto
    depends_on:
      booking-db:
        condition: service_healthy

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  booking-db:
    image: postgres:16
    container_name: booking-db
    environment:
      POSTGRES_DB: ${BOOKING_DB_NAME}
      POSTGRES_USER: ${BOOKING_DB_USER}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASSWORD}
    ports:
      - "5433:5432" # 호스트 5433 -> 컨테이너 5432 (PostgreSQL은 컨테이너 안에서 5432를 리슨)
    volumes:
      - booking_db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${BOOKING_DB_USER} -d ${BOOKING_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
  booking_db_data:
